# Notes:
# - copy this file to `secrets.yaml` (in this folder)
# - edit passwords
api_key: "openssl rand -hex 16 | base64"      # random 32 byte string base-64 encoded
ota_password: "openssl rand -hex 16 | base64" # random 32 byte string base-64 encoded
wifi_ssid: ssid
wifi_password: dmwinniepoopzone
wifi_ap_password: noxingping
