esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# enable logging
logger:

# enable Home Assistant API
api:
  encryption:
    key: !secret api_key

# allow Over-The-Air updates
ota:
  platform: esphome
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${name}
    password: !secret wifi_ap_password

captive_portal:

time:
  - platform: homeassistant
    id: homeassistant_time

debug:
  update_interval: 5s

i2c:
  sda: 21
  scl: 19
  scan: true
  id: bus_a

uart:
  - id: huart1
    rx_pin: 27
    tx_pin: 13
    baud_rate: 9600
  - id: huart2
    rx_pin: 25
    tx_pin: 26
    baud_rate: 9600

sensor:
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal [dB]"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal [%]"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
    device_class: ""

  - platform: debug
    free:
      name: "Heap Free"
    block:
      name: "Heap Max Block"
    loop_time:
      name: "Loop Time"

  - platform: internal_temperature
    name: "MCU Temperature"
    update_interval: 5s

  - platform: bmp280_i2c
    temperature:
      name: "Temperature (BMP280)"
      oversampling: 16x
    pressure:
      name: "Pressure (BMP280)"
    update_interval: 5s
    address: 0x77

  - platform: aht10
    variant: AHT20
    temperature:
      name: "Temperature (AHT20)"
    humidity:
      name: "Humidity (AHT20)"
    update_interval: 5s
    address: 0x38

  - platform: senseair
    co2:
      name: "CO2"
    update_interval: 30s
    uart_id: huart1

  - platform: pmsx003
    type: PMSX003
    pm_1_0:
      name: "ppm <1.0µm"
      id: pm10
    pm_2_5:
      name: "ppm <2.5µm"
      id: pm25
    pm_10_0:
      name: "ppm <10.0µm"
      id: pm100
    update_interval: 60s
    uart_id: huart2

  - platform: template
    id: mpsx_2_5_10
    unit_of_measurement: "µg/m³"
    accuracy_decimals: 2
    icon: mdi:chemical-weapon
    name: "ppm 2.5-10µm"
    lambda: |-
      return id(pm100).state - id(pm25).state;
    update_interval: 60s

  - platform: template
    id: mpsx_1_0_2
    unit_of_measurement: "µg/m³"
    accuracy_decimals: 2
    icon: mdi:chemical-weapon
    name: "ppm 1.0-2.5µm"
    lambda: |-
      return id(pm25).state - id(pm10).state;
    update_interval: 60s

light:
  - platform: binary
    name: "Light"
    output: user_led
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: GPIO23
    num_leds: 2
    chipset: ws2812
    name: "My Light"
output:
  - platform: gpio
    pin: GPIO02
    id: user_led
