substitutions:
  device_id: "01"
  name: esp32-c3-supermini-doorbell-${device_id}
  friendly_name: "Doorbell Sensor(${device_id})"

web_server:

<<: !include esp32-c3-supermini-doorbell-sensor.include.yaml
