esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# enable logging
logger:

# enable Home Assistant API
api:
  encryption:
    key: !secret api_key

# allow Over-The-Air updates
ota:
  platform: esphome
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${name}
    password: !secret wifi_ap_password

captive_portal:

time:
  - platform: homeassistant
    id: homeassistant_time

debug:
  update_interval: 5s

substitutions:
  dummy: "unused"

  run_duration_defaults: &run_duration_defaults
    min_value: 1
    max_value: 300
    step: 1
    initial_value: 5

  valve_defaults: &valve_defaults
    valve_switch_id: dummy_valve_sw

sprinkler:
  - main_switch: "Large Beds 1-3"
    reverse_switch: "Advance Reversed 1-3"
    auto_advance_switch: "Auto Advance 1-3"
    multiplier_number:
      name: "Multiplier 1-3"
      initial_value: 1
      min_value: 0.1
      max_value: 5
    repeat_number:
      name: "Repeat 1-3"
      initial_value: 1
      min_value: 1
      max_value: 5
    # next_prev_ignore_disabled: false              # does not work
    # queue_enable_switch: "Queue Enable"           # ?
    # pump_stop_valve_delay: 1s                     # crashes
    # pump_start_pump_delay: 1s                     # crashes
    # pump_stop_valve_delay: 1s                     # crashes
    # valve_open_delay: 1s                          # 2x too much delay
    # pump_switch_off_during_valve_open_delay: true # 2x too much delay
    valve_overlap: 0s
    standby_switch: "Standby 1-3"

    valves:
      - <<: *valve_defaults
        valve_switch: "Bed 1"
        enable_switch: "Enable Bed 1"
        run_duration_number:
          <<: *run_duration_defaults
          name: "Bed 1 Duration"
        pump_switch_id: pump_sw0
      - <<: *valve_defaults
        valve_switch: "Bed 2"
        enable_switch: "Enable Bed 2"
        run_duration_number:
          <<: *run_duration_defaults
          name: "Bed 2 Duration"
        pump_switch_id: pump_sw1
      - <<: *valve_defaults
        valve_switch: "Bed 3"
        enable_switch: "Enable Bed 3"
        run_duration_number:
          <<: *run_duration_defaults
          name: "Bed 3 Duration"
        pump_switch_id: pump_sw2

  - main_switch: "Small Beds 4-5"
    reverse_switch: "Advance Reversed 4-5"
    auto_advance_switch: "Auto Advance 4-5"
    multiplier_number:
      name: "Multiplier 4-5"
      initial_value: 1
      min_value: 0.1
      max_value: 5
    repeat_number:
      name: "Repeat 4-5"
      initial_value: 1
      min_value: 1
      max_value: 5
    valve_overlap: 0s
    standby_switch: "Standby 4-5"

    valves:
      - <<: *valve_defaults
        valve_switch: "Bed 4 (right)"
        enable_switch: "Enable Bed 4"
        run_duration_number:
          <<: *run_duration_defaults
          name: "Bed 4 Duration"
        pump_switch_id: pump_sw3
      - <<: *valve_defaults
        valve_switch: "Bed 5"
        enable_switch: "Enable Bed 5"
        run_duration_number:
          <<: *run_duration_defaults
          name: "Bed 5 Duration"
        pump_switch_id: pump_sw4

  - main_switch: "Small Beds 6-8"
    reverse_switch: "Advance Reversed 6-8"
    auto_advance_switch: "Auto Advance 6-8"
    multiplier_number:
      name: "Multiplier 6-8"
      initial_value: 1
      min_value: 0.1
      max_value: 5
    repeat_number:
      name: "Repeat 6-8"
      initial_value: 1
      min_value: 1
      max_value: 5
    valve_overlap: 0s
    standby_switch: "Standby 6-8"

    valves:
      - <<: *valve_defaults
        valve_switch: "Bed 6 (center)"
        enable_switch: "Enable Bed 6"
        run_duration_number:
          <<: *run_duration_defaults
          name: "Bed 6 Duration"
        pump_switch_id: pump_sw5
      - <<: *valve_defaults
        valve_switch: "Bed 7"
        enable_switch: "Enable Bed 7"
        run_duration_number:
          <<: *run_duration_defaults
          name: "Bed 7 Duration"
        pump_switch_id: pump_sw6
      - <<: *valve_defaults
        valve_switch: "Bed 8 (left)"
        enable_switch: "Enable Bed 8"
        run_duration_number:
          <<: *run_duration_defaults
          name: "Bed 8 Duration"
        pump_switch_id: pump_sw7

switch:
  - platform: gpio
    id: dummy_valve_sw
    pin: GPIO13
    inverted: true
  - platform: gpio
    id: pump_sw0
    pin: GPIO27
    inverted: true
  - platform: gpio
    id: pump_sw1
    pin: GPIO16
    inverted: true
  - platform: gpio
    id: pump_sw2
    pin: GPIO17
    inverted: true
  - platform: gpio
    id: pump_sw3
    pin: GPIO18
    inverted: true
  - platform: gpio
    id: pump_sw4
    pin: GPIO19
    inverted: true
  - platform: gpio
    id: pump_sw5
    pin: GPIO21
    inverted: true
  - platform: gpio
    id: pump_sw6
    pin: GPIO22
    inverted: true
  - platform: gpio
    id: pump_sw7
    pin: GPIO23
    inverted: true
