substitutions:
  device_id: "01"
  name: esp32-airstation-${device_id}
  friendly_name: "Livingroom Air Sensor (${device_id})"

# esp32_ble_tracker:
# bluetooth_proxy:
web_server:

<<: !include esp32-airstation.include.yaml
