substitutions:
  device_id: "13"
  name: nous-a8t-${device_id}-spare
  friendly_name: "spare (${device_id})"
  max_power: "2000"
  current_res: "0.00126" # higher value gives lower watt readout
  voltage_div: "1570"    # lower value gives lower voltage readout

<<: !include nous-a8t.include.yaml
