substitutions:
  device_id: "05"
  name: nous-a8t-${device_id}
  friendly_name: "3D Printer (${device_id})"
  max_power: "2000"
  current_res: "0.00126" # higher value gives lower watt readout
  voltage_div: "1570"    # lower value gives lower voltage readout

<<: !include nous-a8t.include.yaml
