esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  project:
    name: "NOUS.Smart-Wifi-Socket"
    version: "A8T"
  on_boot:
    priority: 200
    then:
      - if:
          condition:
            switch.is_on: relay
          then:
            - light.turn_on: led
          else:
            - light.turn_off: led

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:

api:
  encryption:
    key: !secret api_key

ota:
  platform: esphome
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap: {}

improv_serial:

captive_portal:

time:
  - platform: homeassistant
    id: homeassistant_time

# esp32_ble_tracker:

# bluetooth_proxy:

globals:
  - id: total_energy
    type: float
    restore_value: true
    initial_value: "0.0"

dashboard_import:
  package_import_url: github://esphome/example-configs/esphome-web/esp32.yaml@main
  import_full_config: true

web_server: # to have a "next url" for improv serial

light:
  - platform: status_led
    internal: True
    name: "Switch state"
    id: led
    pin:
      number: GPIO02
      inverted: true

binary_sensor:
  - platform: gpio
    id: push_button
    internal: true
    pin:
      number: GPIO04
      inverted: yes
      mode: INPUT_PULLUP
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    pin: GPIO13
    id: relay
    name: "Relay"
    restore_mode: ALWAYS_ON
    icon: mdi:power
    on_turn_on:
      - light.turn_on: led
    on_turn_off:
      - light.turn_off: led

sensor:
  - platform: internal_temperature
    name: "MCU Temperature"
    update_interval: 5s

  - platform: wifi_signal
    name: "Wifi Signal"
    update_interval: 60s
    icon: mdi:wifi

  - platform: uptime
    name: "Uptime"
    update_interval: 60s
    icon: mdi:clock-outline

  - platform: hlw8012
    model: BL0937
    sel_pin:
      number: GPIO14
      inverted: True
    cf_pin: GPIO27
    cf1_pin: GPIO26
    current_resistor: ${current_res}
    voltage_divider: ${voltage_div}
    change_mode_every: 1
    update_interval: 5s

    current:
      id: current
      name: "current"
      unit_of_measurement: A
      accuracy_decimals: 3
      icon: mdi:current-ac
      filters:
        - lambda: |-
            if (x < 0.01) return 0;
            else return x;

    voltage:
      id: voltage
      name: "voltage"
      unit_of_measurement: V
      accuracy_decimals: 1
      icon: mdi:flash-outline

    power:
      name: "power"
      id: power
      unit_of_measurement: W
      icon: mdi:flash-outline
      force_update: true
      filters:
        - calibrate_linear:
            - 0.0 -> 0.0
            - 24.50 -> 28.40
      on_value_range:
        - above: ${max_power}
          then:
            - switch.turn_off: relay
            - homeassistant.service:
                service: persistent_notification.create
                data:
                  title: Message from ${name}
                data_template:
                  message: Switch turned off because power exceeded ${max_power}W

  - platform: total_daily_energy
    name: "energy"
    power_id: power
    state_class: total_increasing
    unit_of_measurement: kWh
    filters:
      # multiplication factor from W to kW is 0.001
      - multiply: 0.001
      - lambda: !lambda |-
          static auto last_state = x;
          if (x < last_state) { // x was reset
            id(total_energy) += last_state;
            ESP_LOGI("main", "Energy was reset: %f", id(total_energy));
          }
          last_state = x;
          return id(total_energy) + x;
