substitutions:
  name: nous-a8t-xx

esphome:  
  name: ${name}
  platformio_options:
    board_build.flash_mode: dio
    
esp32:
  board: esp32doit-devkit-v1  
  framework:  
    type: esp-idf  
    platform_version: 6.4.0  
    version: 5.1.1

wifi:  
  manual_ip:  
    static_ip: 192.168.2.28
    gateway: 192.168.2.1
    subnet: 255.255.255.0  
    dns1: 192.168.2.5
  id: wifiId
  ssid: IoT
  password: nocnwinniepoop
  ap: {}

ota:  
  unprotected_writes: True # This is mandatory if you want to flash the partition table or bootloader!     

logger:
web_server:
button:
