# Brief instructions:
#
# 1. edit wifi-> manual_ip
# 2. `esphome compile test.yaml`
# 3. upload compiled file via tasmota website -> reboot
# 4. `esphome -v upload-factory-ota test.yaml`
#
# Detailed instructions:
# [1] https://devices.esphome.io/devices/Nous-A8T
# [2] steps 21 to 32: https://github.com/kadam12g/ESPHome-Shelly-Plus-Plug-S?tab=readme-ov-file
#
# Notes:
# - this file must be named `test.yaml` according to [2]
# - `esphome` command must be invoked   according to [2]

substitutions:
  name: nous-a8t-xx

esphome:  
  name: ${name} # will announce via mDNS as ${name}.local
  platformio_options:
    board_build.flash_mode: dio
    
esp32:
  board: esp32doit-devkit-v1  
  framework:  
    type: esp-idf  
    platform_version: 6.4.0  
    version: 5.1.1

wifi:  
  manual_ip:  
    static_ip: 192.168.0.101
    gateway:   192.168.0.1
    subnet:    255.255.255.0
    dns1:      192.168.0.1
  id: wifiId
  ssid: "Mc Muck Free Wifi"
  password: nocnwinniepoop
  ap: {}

ota:  
  unprotected_writes: True # Mandatory if you want to flash the partition table or bootloader!

logger:
web_server:
button:
